
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2019.2.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2020 Xilinx, Inc. All Rights Reserved.*
*Permission is hereby granted, free of charge, to any person obtaining a copy
*of this software and associated documentation files (the Software), to deal
*in the Software without restriction, including without limitation the rights
*to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*copies of the Software, and to permit persons to whom the Software is
*furnished to do so, subject to the following conditions:
*
*The above copyright notice and this permission notice shall be included in
*all copies or substantial portions of the Software.
* 
*THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
*THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
*WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
*OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xbram.h"

/*
* The configuration table for devices
*/

XBram_Config XBram_ConfigTable[] =
{
	{
		XPAR_BASE_MOD_SCRATCH_BRAM_CTRL_DEVICE_ID,
		XPAR_BASE_MOD_SCRATCH_BRAM_CTRL_DATA_WIDTH,
		XPAR_BASE_MOD_SCRATCH_BRAM_CTRL_ECC,
		XPAR_BASE_MOD_SCRATCH_BRAM_CTRL_FAULT_INJECT,
		XPAR_BASE_MOD_SCRATCH_BRAM_CTRL_CE_FAILING_REGISTERS,
		0,
		XPAR_BASE_MOD_SCRATCH_BRAM_CTRL_UE_FAILING_REGISTERS,
		0,
		XPAR_BASE_MOD_SCRATCH_BRAM_CTRL_ECC_STATUS_REGISTERS,
		XPAR_BASE_MOD_SCRATCH_BRAM_CTRL_CE_COUNTER_WIDTH,
		XPAR_BASE_MOD_SCRATCH_BRAM_CTRL_ECC_ONOFF_REGISTER,
		XPAR_BASE_MOD_SCRATCH_BRAM_CTRL_ECC_ONOFF_RESET_VALUE,
		XPAR_BASE_MOD_SCRATCH_BRAM_CTRL_WRITE_ACCESS,
		XPAR_BASE_MOD_SCRATCH_BRAM_CTRL_S_AXI_BASEADDR,
		XPAR_BASE_MOD_SCRATCH_BRAM_CTRL_S_AXI_HIGHADDR,
		XPAR_BASE_MOD_SCRATCH_BRAM_CTRL_S_AXI_CTRL_BASEADDR,
		XPAR_BASE_MOD_SCRATCH_BRAM_CTRL_S_AXI_CTRL_HIGHADDR
	},
	{
		XPAR_DMA_XDMA_BRAM_CTRL_DEVICE_ID,
		XPAR_DMA_XDMA_BRAM_CTRL_DATA_WIDTH,
		XPAR_DMA_XDMA_BRAM_CTRL_ECC,
		XPAR_DMA_XDMA_BRAM_CTRL_FAULT_INJECT,
		XPAR_DMA_XDMA_BRAM_CTRL_CE_FAILING_REGISTERS,
		0,
		XPAR_DMA_XDMA_BRAM_CTRL_UE_FAILING_REGISTERS,
		0,
		XPAR_DMA_XDMA_BRAM_CTRL_ECC_STATUS_REGISTERS,
		XPAR_DMA_XDMA_BRAM_CTRL_CE_COUNTER_WIDTH,
		XPAR_DMA_XDMA_BRAM_CTRL_ECC_ONOFF_REGISTER,
		XPAR_DMA_XDMA_BRAM_CTRL_ECC_ONOFF_RESET_VALUE,
		XPAR_DMA_XDMA_BRAM_CTRL_WRITE_ACCESS,
		XPAR_DMA_XDMA_BRAM_CTRL_S_AXI_BASEADDR,
		XPAR_DMA_XDMA_BRAM_CTRL_S_AXI_HIGHADDR,
		XPAR_DMA_XDMA_BRAM_CTRL_S_AXI_CTRL_BASEADDR,
		XPAR_DMA_XDMA_BRAM_CTRL_S_AXI_CTRL_HIGHADDR
	}
};


